### ISSUE TITLE
Add SWAG reverse proxy integration

### ISSUE THREAD

**Issue by TheRedCyclops** [sablierapp/sablier#401] opened 2024-09-13 18:26 UTC
**Describe the reverse proxy you'd like**
From README:
SWAG - Secure Web Application Gateway (formerly known as letsencrypt, no relation to Let's Encrypt™) sets up an Nginx webserver and reverse proxy with php support and a built-in certbot client that automates free SSL server certificate generation and renewal processes (Let's Encrypt and ZeroSSL). It also contains fail2ban for intrusion prevention.

**Does the reverse proxy provides middleware/module/extension support**
Uses Nginx so it also uses modules

**Additional context**
I have tried to just add Sablier in the same way that I added Sablier to Nginx and I couldn't get it to work, I did get js module support working  in the same way that I did for the dockerized version of nginx packaged by linuxserver.io,
To add it these env vars have to be added 
```
DOCKER_MODS=linuxserver/mods:universal-package-install
INSTALL_PACKAGES=nginx-mod-http-js
```
The loading of the js support has to be omitted as it is done automatically and it will error out if it's done again

**Comment by acouvreur** [comment] 2024-10-25 03:39
Because SWAG is based on nginx, I think you could achieve this at some point ? Depending on how SWAG allows you to customize ?

I know this feature is asked a lot, so if you actually succeed in doing so, please share how you did it and I will add it to the docs.

But this feature request has already been asked here: https://github.com/sablierapp/sablier/issues/110.

So I'm closing this issue as duplicate of https://github.com/sablierapp/sablier/issues/110.

**Closed by acouvreur** 2024-10-25 03:39 UTC
Labels: enhancement, reverse-proxy
